version: '3.8'

services:
  app:
    image: alejandrodevelop3r/ever-carvajal-par2:1.0
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - MYSQL_DATABASE=myapp
      - DB_HOST=db
    networks:
      - app-network

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: myapp
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
